### PR TITLE
remove file details from grouped coverage md report

### PR DESCRIPTION
**Pull request by abhinavrastogi-harness**
For large repos like `harness-core-ui` the number of files has become large enough that Github is not able to render the grouped coverage markdown report. We can plan to publish the file-level details to a separate report for each module in a separate PR.

### CODE REVIEW

**Review by vkbansal-harness — APPROVED** [review]

**Comment by abhinavrastogi-harness** [comment]
@vkbansal-harness it seems the automation checks are broken.. can you check? or should we FM?

**Comment by vkbansal-harness** [comment]
Merge it

**Comment by abhinavrastogi-harness** [comment]
@vkbansal-harness new release will happen automatically?

**Comment by vkbansal-harness** [comment]
Not sure

**Pull request merged**
